/**
 * This class is generated by jOOQ
 */
package appengine.parser.mysqlmodels.tables;


import appengine.parser.mysqlmodels.Parser;
import appengine.parser.mysqlmodels.enums.CointransferCurrentstate;
import appengine.parser.mysqlmodels.tables.records.CointransferRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cointransfer extends TableImpl<CointransferRecord> {

    private static final long serialVersionUID = -1804982989;

    /**
     * The reference instance of <code>parser.cointransfer</code>
     */
    public static final Cointransfer COINTRANSFER = new Cointransfer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CointransferRecord> getRecordType() {
        return CointransferRecord.class;
    }

    /**
     * The column <code>parser.cointransfer.coin</code>.
     */
    public final TableField<CointransferRecord, String> COIN = createField("coin", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * The column <code>parser.cointransfer.amount</code>.
     */
    public final TableField<CointransferRecord, Double> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>parser.cointransfer.pricetobespentinbtc</code>.
     */
    public final TableField<CointransferRecord, Double> PRICETOBESPENTINBTC = createField("pricetobespentinbtc", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>parser.cointransfer.profitestimatedinbtc</code>.
     */
    public final TableField<CointransferRecord, Double> PROFITESTIMATEDINBTC = createField("profitestimatedinbtc", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>parser.cointransfer.buymarket</code>.
     */
    public final TableField<CointransferRecord, String> BUYMARKET = createField("buymarket", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * The column <code>parser.cointransfer.sellmarket</code>.
     */
    public final TableField<CointransferRecord, String> SELLMARKET = createField("sellmarket", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

    /**
     * The column <code>parser.cointransfer.maxbuyprice</code>.
     */
    public final TableField<CointransferRecord, Double> MAXBUYPRICE = createField("maxbuyprice", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>parser.cointransfer.minsellprice</code>.
     */
    public final TableField<CointransferRecord, Double> MINSELLPRICE = createField("minsellprice", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>parser.cointransfer.currentstate</code>.
     */
    public final TableField<CointransferRecord, CointransferCurrentstate> CURRENTSTATE = createField("currentstate", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(appengine.parser.mysqlmodels.enums.CointransferCurrentstate.class), this, "");

    /**
     * The column <code>parser.cointransfer.updatedtime</code>.
     */
    public final TableField<CointransferRecord, Timestamp> UPDATEDTIME = createField("updatedtime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>parser.cointransfer.buyorderid</code>.
     */
    public final TableField<CointransferRecord, String> BUYORDERID = createField("buyorderid", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>parser.cointransfer.sellorderid</code>.
     */
    public final TableField<CointransferRecord, String> SELLORDERID = createField("sellorderid", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>parser.cointransfer.buyfilledamount</code>.
     */
    public final TableField<CointransferRecord, Double> BUYFILLEDAMOUNT = createField("buyfilledamount", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>parser.cointransfer.sellfilledamount</code>.
     */
    public final TableField<CointransferRecord, Double> SELLFILLEDAMOUNT = createField("sellfilledamount", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>parser.cointransfer</code> table reference
     */
    public Cointransfer() {
        this("cointransfer", null);
    }

    /**
     * Create an aliased <code>parser.cointransfer</code> table reference
     */
    public Cointransfer(String alias) {
        this(alias, COINTRANSFER);
    }

    private Cointransfer(String alias, Table<CointransferRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cointransfer(String alias, Table<CointransferRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Parser.PARSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cointransfer as(String alias) {
        return new Cointransfer(alias, this);
    }

    /**
     * Rename this table
     */
    public Cointransfer rename(String name) {
        return new Cointransfer(name, null);
    }
}
